### ISSUE TITLE
Migrar atual G-Suite promocional dos emails ok.org.br para um definitivo e igualmente gratuito

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/suporte#10]
A OKBR vem administrando seus e-mails `fulano@ok.org.br` através da plataforma [G Suite](https://en.wikipedia.org/wiki/G_Suite), pois inscreveu-se num plano promocional gratuito, mas o mesmo  vence em 2017. Não há como renovar a promoção, e o custo seria da ordem de US$5 por usuário.

Temos atualmente 44 usuários registrados, mas por volta de 20 com alguma atividade. Seriam portanto da ordem de US$100/mês a US$200/mês de despesa (R$300 a R$600), sendo que num servidor Linux próprio (que já temos) podemos gerenciar uma infinidade de contas de email, "sem" custo &mdash; com custo inicial de instalação e depois de suporte. 

A **melhor solução** é continuar usando G Suite *sem custo*: isso é possível, através do plano [*for-nonprofits*](https://www.google.com/nonprofits/products/apps-for-nonprofits.html), pois a OKBr é  reconhecida e inscrita juridicamente como entidade sem fins lucrativos. 

**Solicitação** de suporte técnico/administrativo da diretoria da OKBr: avaliar como migrar do atual plano promocional para um definitivo tipo *for-nonprofits*.  Cadastrar-se se não houverem maiores impactos. <br/>PS: além das caixas de e-mail pode-se fazer uso de outros serviços, tais como [CRM](https://pt.wikipedia.org/wiki/Customer_relationship_management).

**Comment by everton137** [comment]
@ppKrauss , nosso plano é para organizações sem fins lucrativos (non profits). Me inscrevi no Techsoup Brasil para viabilizar isso e fui informado que não havia limite. Onde viu que há um limite até final de 2017? Acabei de checar nosso plano na seção 'Faturamento' e está como non profit.

**Comment by ppKrauss** [comment]
Oi gente, desculpem, realmente não é o  "plano promocional", CANCELANDO E FECHANDO esta issue, **erro de interpretação**.

Obrigado @everton137 pela sua verificação no Faturamento.
