### ISSUE TITLE
Wordpress OKBr precisaria desativar emissão automatica de Tweets

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/suporte#5]
Copiando trecho de e-mail da Elza que explica a demanda,

> (...) Há um tempo estou tentando descobrir a publicação automática que temos atualmente no Twitter. Assim que publicamos uma nota no blog, ele faz um tweet. Gostaria de desativar isso no blog, mas não consegui. (...)

**Comment by everton137** [comment]
Eu posso desativar. Estamos usando o Feedburner. Mas não é útil essa função? Vi várias pessoas retweetando e gostando de posts nossos automáticos...

**Comment by arielkogan** [comment]
Melhor desligar mesmo

Em 24 de mai de 2017 10:09, "Tom" <notifications@github.com> escreveu:

**Comment by ppKrauss** [comment]
Concluindo: desligando e Ton passando administração do Feedburner para a Elza.
